### ISSUE TITLE
Unable to deserialize an OPDS2 feed

### ISSUE THREAD

**Issue by clebeaupin** [edrlab/r2-opds-js#6] opened 2018-12-26 10:13 UTC
Feed: https://feedbooks.github.io/opds-test-catalog/opds-2/home.json

Calling this method 
`opds2Feed = TAJSON.deserialize<OPDSFeed>(JSON.parse(opdsFeedData),  OPDSFeed);
`
raises an error 
`
TypeError: arr.map is not a function
 at deserializeArray (/home/clebeaupin/projects/edrlab/readium-desktop/node_modules/ta-json-x/dist/cjs/methods/deserialize.js:53:1
`

**Comment by HadrienGardeur** [comment] 2018-12-26 14:56
The reference test catalog for OPDS 2.0 is now located at https://test.opds.io/2.0/home.json

You should also test the Feedbooks OPDS 2.0 catalog at https://catalog.feedbooks.com/catalog/index.json

**Comment by danielweck** [comment] 2018-12-26 17:55
Thank you for reporting the bug. I am able to reproduce it. Investigating ...

**Comment by danielweck** [comment] 2018-12-26 18:11
Oh I see, `metadata.author` is a TypeScript "union type" of:
* `string` (e.g. "daniel")
* `object` ("language map" such as `{ "fr": "daniel" }`)
* `object` ( full data structure `{ name, sortAs, identifier, role, links[], images[] }`, where `name` is either `string` or "language map" `object`)
* array of any of the above 3 different types.

Problems to solve:

* Daniel: fix the OPDS / TA-JSON parser to handle all edge cases.
* Cyrille: make sure that the "union type" variants are handled correctly in database / UI / etc.

**Comment by danielweck** [comment] 2018-12-26 18:15
JSON Schema references:
https://github.com/opds-community/drafts/blob/master/schema/publication.schema.json
=>
https://github.com/readium/webpub-manifest/blob/master/schema/contributor.schema.json
=>
https://github.com/readium/webpub-manifest/blob/master/schema/contributor-object.schema.json

**Comment by danielweck** [comment] 2018-12-27 08:54
FYI - I'm doing a review pass on the JSON-Schema as I am cross-referencing the TypeScript model, and I found a few issues:
https://github.com/readium/webpub-manifest/issues

I am currently checking the ReadiumWebPubManifest schema (in progress), but will soon get to the OPDS2 stuff ...

**Comment by danielweck** [comment] 2018-12-29 04:50
Fixed in `r2-opds-js` v`1.0.5` and `r2-shared-js` v`1.0.6`.
Please upgrade your packages: `npm update --save r2-shared-js r2-opds-js` (although I would recommend `rm -rf node_modules && rm package-lock.json && npm install` to ensure a clean dependency tree).

Tested with OPDS2 feeds+publications from spec. maintainers and from Feedbooks (there are automated unit tests with recursive browsing/crawling of public URLs). Also manually tested via `r2-streamer-js` to check JSON Schema validation (by using the locally-generated OPDS2 feed, and feeds/publications converted from OPDS1). Tested with complex Japanese metadata (local EPUB files) sets that exhibit edge-cases for the combination of aforementioned union types.

**Comment by danielweck** [comment] 2018-12-29 04:51
Reminder of the OPDS2 feed URLs for the deployed streamer instances:
https://readium2.herokuapp.com/opds2/publications.json/show
https://readium2.now.sh/opds2/publications.json/show

**Comment by danielweck** [comment] 2018-12-29 04:55
Showcase of metadata variants with `kusamakura-japanese-vertical-writing`:
https://github.com/IDPF/epub3-samples/tree/master/30/kusamakura-japanese-vertical-writing
( https://github.com/IDPF/epub3-samples/releases/download/20170606/kusamakura-japanese-vertical-writing.epub )

=>

https://readium2.herokuapp.com/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAva3VzYW1ha3VyYS1qYXBhbmVzZS12ZXJ0aWNhbC13cml0aW5nL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

https://readium2.now.sh/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAva3VzYW1ha3VyYS1qYXBhbmVzZS12ZXJ0aWNhbC13cml0aW5nL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

**Comment by danielweck** [comment] 2018-12-29 05:00
Another showcase with `regime-anticancer-arabic`:
https://github.com/IDPF/epub3-samples/tree/master/30/regime-anticancer-arabic
( https://github.com/IDPF/epub3-samples/releases/download/20170606/regime-anticancer-arabic.epub )

=>

https://readium2.herokuapp.com/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAvcmVnaW1lLWFudGljYW5jZXItYXJhYmljL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

https://readium2.now.sh/pub/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0lEUEYvZXB1YjMtc2FtcGxlcy9tYXN0ZXIvMzAvcmVnaW1lLWFudGljYW5jZXItYXJhYmljL01FVEEtSU5GL2NvbnRhaW5lci54bWw%3D/manifest.json/show/all

**Comment by danielweck** [comment] 2018-12-29 05:07
Reminder of useful public OPDS URLs (mostly OPDS1):
https://github.com/readium/r2-streamer-js/blob/develop/docs/opds.md#a-selection-of-public-opds-feeds

**Comment by danielweck** [comment] 2018-12-29 05:15
As mentioned by Hadrien, the Feedbooks feed is available as OPDS2, but here is a dynamic conversion from OPDS1 which is useful for testing / comparing (as I assume the reader apps will still need to consume OPDS1):

(replace `https://readium2.herokuapp.com` with `https://readium2.now.sh` if the server fails because of exceeded bandwidth)

Navigation:
https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fwww.feedbooks.com%2Fcatalog.atom

=>

Top publications:
https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fpublicdomain%2Fbrowse%2Fen%2Ftop.atom%3Frange%3Dmonth

=>

Publication:
https://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fcatalog.feedbooks.com%2Fbook%2F1421.atom

**Closed as completed** 2018-12-29 05:16 UTC
